- id: '1568221947523'
  alias: Turn Lights On at Sunset
  trigger:
  - event: sunset
    offset: '-1:00'
    platform: sun
  condition: []
  action:
  - data:
      entity_id: all
    service: light.turn_on
- id: '1569335631762'
  alias: Fountain On
  trigger:
  - platform: webhook
    webhook_id: fountain-switch-on
  condition: []
  action:
  - data:
      entity_id: switch.fountain
    service: switch.turn_on
- id: '1569336206494'
  alias: Fountain Off
  trigger:
  - platform: webhook
    webhook_id: fountain-switch-off
  condition: []
  action:
  - alias: ''
    data:
      entity_id: switch.fountain
    service: switch.turn_off
